### ISSUE TITLE
Do not try do delete `testing` branch anymore

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#165]
In #134, we transitioned from testing on `testing/<id>` instead of just `testing`.  In order to maintain backwards compatibility, we had to delete `testing` every time we created a new `testing/<id>` branch.

That has been a month ago, and most projects that use Hoff should have had at least one PR triggering the deletion of `testing`.  So we should remove this code that tries deletion every time.

We currently see the following in the logs every time we merge:

```haskell
Aug 18 13:37:12 hoff hoff[4321]: [Warn] error: git push -d failed. Reason: error: unable to delete 'testing': remote ref does not exist
Aug 18 13:37:30 hoff hoff[4321]: error: failed to push some refs to 'git@github.com:<org>/<repo>.git'
```

This should get rid of entries like the above.

### TODO

- [x] check that _all projects/repos_ do not have a `testing` branch anymore
   - [x] delete any found
- [x] remove the testing deletion code: #173
- [ ] double-check that _all projects/repos_ do not have a `testing` branch anymore

**Comment by rudymatela** [comment]
Thanks to @tomwassenberg for helping me with the deletion in some repos!  :smile: :tada:
