### ISSUE TITLE
Only unintegrate after closing unfailed pull requests

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#184]
~There was an instance of a rebase being triggered by a PR closure.  This should not happen:~

PRs 19 and 36 were closed in that order at: 13:25:59 and 13:26:00.  Seemingly, closure of PR 36 caused it to be rebased, but actually that was caused by the closure of 19:

![rebase-after-closing](https://user-images.githubusercontent.com/3999598/188132283-4e008d62-d4f5-4b82-aee0-83c0df1a0e35.png)

There is still a bug here: the closure of 19 should not have triggered a rebase of 36 as it had already failed.  The `handlePullRequestClosure` logic has to be fixed.  We should only `unintegrateAfter` when the PR being closed is `unfailedIntegrated`.

(Thanks to @Gijsvs for reporting.)

## TODO

- [x] add failing regression test
- [x] (think about the fact that that 36 was already failed... its approval was outdated already, shouldn't have been integrated either way... -- update: I think with just the fix of the item below this should be prevented)
- [x] only unintegrate after unfailingIntegrated PRs

**Comment by rudymatela** [comment]
Here's how to extract the relevant logs:

```bash
journalctl -S "2022-09-02 13:23" -U "2022-09-02 13:28" -uhoff >closure-triggering-rebase.log
```
