### ISSUE TITLE
Hoff stalls when rebase results in empty branch

### ISSUE THREAD

**Issue by fatho** [channable/hoff#75]
In rare occasions it can happen that rebasing a branch on top of master leaves it empty. This is the case when all the changes from the branch have already been applied to master in the meantime. Git will then omit the empty commits, and have the branch point to the latest commit on master directly.

But since that way, no new commit is generated, no CI job is spawned, and thus Hoff never gets the webhook for the CI result, causing it to hang indefinitely.

When encountering an empty branch after rebasing, Hoff should post a comment and abandon that PR.

### TODO

* [x] reproduce the issue in an automated test
* [x] reproduce the issue in @OpsBotPrime 
* [x] fix the issue
* [x] add automated tests
* [x] self code review of #115
* [x] address reviewer's comments on #115
* [ ] merge and deploy #115 
* [ ] try to reproduce the issue in @OpsBotPrime again

**Comment by rudymatela** [comment]
To simulate this on git one can use `master` and two branches `first` and `second`.

1. start with just `master`:

    ![just-master](https://user-images.githubusercontent.com/3999598/170025720-d00e52e3-0215-402c-a6fb-6be013f4ea6f.png)

2. fork the `first` branch from `master` and commit

3. fork the `second` branch from the `first` and commit again

4. checkout `master` and commit for good measure, the commit tree should now look like the following:

    ![three-branches](https://user-images.githubusercontent.com/3999598/170026480-156aa48d-9123-41cd-b069-b80c2ca9482a.png)
 
5. checkout `second`, rebase it into master, merge it into master.  Now the commit tree should have duplicate commits:

   ![duplicate-commits](https://user-images.githubusercontent.com/3999598/170026915-aac4f1ba-03ad-4d04-9332-b7fc8b07b2bf.png)

6. that is allright, as git can detect it.  Just checkout `first`, rebase it into master and you'll see that the tree should just be pruned like so:

    ![pruned](https://user-images.githubusercontent.com/3999598/170027146-9131d052-bfa6-4ccd-aa81-28760748d60b.png)

I believe this would be able to trigger Hoff's bug.

**Comment by fatho** [comment]
But in that situation, we would get a merge commit (it seems that you didn't merge `second` with `--no-ff` in your example). Does that change things?

We already cover a similar case: when you set the base branch of `second` to `first` (rather than `master`) in the GitHub PR view, then we already refuse merging `second` I believe. But of course if you leave the base branch unchanged, we cannot detect this situation - and we only notice it at rebase-time.

**Comment by rudymatela** [comment]
> But in that situation, we would get a merge commit (it seems that you didn't merge `second` with `--no-ff` in your example). Does that change things?

Good point.  I will try this and report the results here.

**Comment by rudymatela** [comment]
This is how the commit graph looks after the `--no-ff` merge:

![after-no-ff-merge](https://user-images.githubusercontent.com/3999598/170031992-526e30a2-977d-4802-b6b0-f93b97f436af.png)

After rebasing `first`, the result is the same, the commit graph is just pruned.

![after-rebasing-first](https://user-images.githubusercontent.com/3999598/170032005-2815c13e-d4c7-4e37-ab4f-9ec0621fa1d8.png)

So I think this should still trigger the Hoff bug.

(I've noticed it's not a tree anymore but a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph).)

**Comment by rudymatela** [comment]
@fatho Quick question about this issue.  What is the scope of Hoff stalling?

* Does Hoff stall globally?  Does it stop working for all projects?
* Does Hoff stall on the project?  Does it stop working for the specific project?
* Does Hoff stall on the PR?  Does it stop working just for the specific PR?

I am guessing it is the third one, right?  :thinking: :thought_balloon:

**Comment by fatho** [comment]
It starts with the latter, but it cascades to the whole project. The description from the original issue text could be made more concrete like this:

> [...] But since that way, no new commit is generated, no CI job is spawned, and thus Hoff never gets the webhook for the CI result, causing it to make no progress on the PR indefinitely. This causes the PR to block the merge queue for the corresponding project forever (until manually closed).

So it's not "hanging" in the strict sense - mainly waiting for an event that never comes. But it still reacts to other events, such as you manually closing the PR.

**Comment by rudymatela** [comment]
Noted.  Thanks for the clarification.  This will make it easier on the testing side (I can play with OpsBotPrime without making it stuck for everyone)
